### PR TITLE
Move webserver root to «public», rename codeigniter stuff to identify…

### PR DESCRIPTION
**Pull request by vibby**
Here a structural small step improvement.
Modern applications do not expose all their stuff to webserver at root.
A webserver root inside the project is a good practice to isolate what can be given through http, what must not. For example, it is possible to download template with the url http://www.adventistcommons.com/application/views/twig/editor.twig

That is why I create a ```public``` folder with all stuff exposed. It was just a test in the beginning that worked so well, I decided to push it here.
By the way, I renamed the ```system``` to ```codeIgniterSystem``` to clarify stuff.

I also made a symlink to the uploads directory but this not a good idea. We have to check rights before serving files. For example, it is possible for someone with url to download IDML without even being connected :/ A solution must be found here.

Another further step would be to install codeigniter’s system with composer. Seems pretty easy. I’ll try some day.

### CODE REVIEW

**Comment by davrv93** [comment]
Well actually you can't get the files since is proxied by nginx by the port of the apache server. Nginx is configured for read the port and by the htaccess readed by apache it doesnt return the files. I don't know if it would be necessary also

**Comment by davrv93** [comment]
image
I have tested it and it's like I told you, you can't get the files by the url, but I will check the suggestions, every help is always a blessing and also well received, God bless you !

**Comment by vibby** [comment]
A good point in security is not to rely on other parts. The files and folder access is managed by apache, that can be misconfigurated, or have security breach. Or we could switch to full nginx (like the docker config).
Here is an example of file accessible : http://develop.adventistcommons.org/docker/mysql/init.sql because there is no .htaccess file.
It’s pretty much clear to see what goes to webserver, what does not, directly in the files, without to have to trust htaccess files or apache config.

Of course, it is not absolutely needed, but from my point of view, it’s a small-effort global security point, that has no side effect.

**Comment by davrv93** [comment]
> A good point in security is not to rely on other parts. The files and folder access is managed by apache, that can be misconfigurated, or have security breach. Or we could switch to full nginx (like the docker config).
> Here is an example of file accessible : http://develop.adventistcommons.org/docker/mysql/init.sql because there is no .htaccess file.
> It’s pretty much clear to see what goes to webserver, what does not, directly in the files, without to have to trust htaccess files or apache config.
> 
> Of course, it is not absolutely needed, but from my point of view, it’s a small-effort global security point, that has no side effect.

You are right ! we can implement your suggestion and as we talk before we will disable the browser directory of apache  by the vhost ( For prevent something like this: 

image
)

Thanks Vincent ! God bless you

**Pull request merged**
