### PR TITLE
Add languages and skills to profile page

### PR DESCRIPTION
**Pull request by rafaelji**
image

### CODE REVIEW

**Comment by rafaelji** [comment]
[Allow editing of "languages" and "skills" in profile settings](https://trello.com/c/I1XGqhQw/26-allow-editing-of-languages-and-skills-in-profile-settings)

**Comment by m-dotcom** [comment]
@rafaelji Could you also make the "mother language" editable. It is important for us to know which languages is the users heart language, so we should have a separate option for that just as in the sign up process. 
Screen Shot 2019-07-07 at 9 16 16 PM

**Comment by akjackson1** [comment]
@rafaelji this appears to be a duplicate of https://github.com/AdventistCommons/adventistcommons.org/pull/27
I hate to see the work go to waste, but we don't need two of the same thing 😞

**Comment by rafaelji** [comment]
No problem @akjackson1 , these situations happens! ;)

**Pull request closed without merging**
