### PR TITLE
Add FAQ page card

### PR DESCRIPTION
**Pull request by WarlenOliveira**
-Add FAQ page
-Rename the item "Translations in Progress" to "Ongoing Translations"

Because this is my first contribution to the project and my first contact with PHP, I ask that you please check the files with attention.

### CODE REVIEW

**Comment by WarlenOliveira** [comment]
Thank you for your comment Samuel. It is the same on my browser. Could you please help me with this? what should I change in the code in order to make it works? 

Blessings.

**Comment by vibby** [comment]
This is because of header with the menu, it «hides» the beginning of the content …
A solution is to give a margin-top to man content bx the height of the header.
Regards

**Comment by vibby** [comment]
Here is a solution. Not perfect, frontend experts may find better :
Add
```style="margin-top: 3em;padding-top: 3em;"```
to every
```<a name="xxxxx"```
you can do it on terms_of_use and privacy_policy too please

**Comment by WarlenOliveira** [comment]
Updated.
Please test all the links to make sure that they are working before merge.

**Comment by davrv93** [comment]
HI Warlen, I have fixed the last 2 redirects, now itws working so I will make the merge , thanks ! Lord Bless you

**Pull request merged**
